/* ==========================================================================
   BranchBook 논문 자료 — 10장(종합)과 11장(참고문헌)이 함께 쓴다.
   수치는 각 논문이 밝힌 조건에서 보고한 값이다. 조건이 다른 논문끼리 직접 비교할 수 없다.
   evidence: 이 책이 확인한 근거의 범위(논문 전문 / 공개 초록 / 판본 구분).
   ========================================================================== */
(function () {
  "use strict";

  const WORKLOAD_FAMILIES = {
    general: { label: "SPEC · GAP", seriesIndex: 0 },
    server: { label: "서버 · 데이터센터", seriesIndex: 1 },
    trace: { label: "CBP trace", seriesIndex: 2 },
  };

  const INFORMATION_KINDS = {
    history: "History를 더 잘 읽는다",
    value: "값과 선행 계산을 쓴다",
    state: "예측 상태를 관리한다",
    recovery: "준비해 둔 결과를 쓴다",
  };

  const INTERVENTION_TIMES = {
    prediction: "예측하는 순간",
    beforeResolve: "예측한 뒤, 확인하기 전",
    afterMisprediction: "오예측이 드러난 뒤",
  };

  const PAPERS = [
    {
      id: "branchnet", name: "BranchNet", category: "A", venue: "MICRO 2020", year: 2020,
      title: "BranchNet: A Convolutional Neural Network to Predict Hard-To-Predict Branches",
      authors: "Zangeneh, Pruett, Lym, Patt",
      url: "https://hps.ece.utexas.edu/pub/BranchNet_Micro2020.pdf",
      chapter: "correlation", anchor: "branchnet",
      information: "history", intervention: "prediction", workloadFamily: "general",
      idea: "Offline에서 학습한 CNN이 noise가 섞인 긴 history에서 위치와 무관하게 상관을 찾는다.",
      needs: "여러 입력으로 미리 학습해야 하고, 그 상관이 새 입력에서도 유지되어야 한다.",
      baseline: "64KB TAGE-SC-L", workload: "SPEC2017 정수", core: "논문의 OoO 모델",
      misprediction: [{ label: "Mini-BranchNet 평균", value: 9.6 }],
      speedup: [{ label: "Mini-BranchNet 기하평균", value: 1.3 }],
      cost: "분기별 모델 저장 공간, offline 학습과 배포",
      evidence: "논문 전문",
    },
    {
      id: "runahead", name: "Branch Runahead", category: "B", venue: "MICRO 2021", year: 2021,
      title: "Branch Runahead: An Alternative to Branch Prediction for Impossible to Predict Branches",
      authors: "Pruett, Patt",
      url: "https://utw10235.utweb.utexas.edu/pub/PruettPatt_BranchRunahead.pdf",
      chapter: "value", anchor: "runahead",
      information: "value", intervention: "prediction", workloadFamily: "general",
      idea: "분기 결과에 필요한 계산(dependence chain)만 별도 엔진에서 먼저 실행해 결과를 fetch 전에 건넨다.",
      needs: "결과가 해당 분기의 fetch보다 먼저 도착해야 한다. chain이 단순해야 한다.",
      baseline: "64KB TAGE-SC-L", workload: "SPEC2006/2017 정수 + GAP 중 MPKI > 2인 17개", core: "4-wide",
      misprediction: [{ label: "Mini 구성 평균", value: 43.6 }],
      speedup: [{ label: "Mini 구성 평균", value: 13.7 }],
      cost: "Mini 구성 17KB, 보조 실행 엔진과 queue",
      evidence: "논문 전문",
    },
    {
      id: "tea", name: "TEA", category: "B", venue: "MICRO 2024", year: 2024,
      title: "TEA: Timely, Efficient, and Accurate Branch Precomputation",
      authors: "Deshmukh, Cai, Patt",
      url: "https://hps.ece.utexas.edu/pub/TEA.pdf",
      chapter: "value", anchor: "tea",
      information: "value", intervention: "beforeResolve", workloadFamily: "general",
      idea: "미리 계산한 결과가 예측과 다르면 분기가 실행되기를 기다리지 않고 일찍 flush한다.",
      needs: "결과가 분기의 실행보다 먼저 나오면 된다. 같은 코어의 자원을 main과 나눠 쓴다.",
      baseline: "64KB TAGE-SC-L", workload: "SPEC2017 + GAP", core: "8-wide",
      misprediction: [],
      speedup: [{ label: "기하평균", value: 10.1 }],
      cost: "동적 명령 +31.9%, 면적 +3.5%",
      evidence: "논문 전문",
    },
    {
      id: "runlts", name: "RUNLTS", category: "B", venue: "CBP2025 · ISCA 2026", year: 2026,
      title: "RUNLTS: Register-value-aware predictor Utilizing Nested Large TableS",
      authors: "Koizumi, Maekawa, Mizuno, Tsumura, Kuroki, Shioya",
      url: "https://ericrotenberg.wordpress.ncsu.edu/files/2025/06/cbp2025-final44-Koizumi.pdf",
      chapter: "value", anchor: "runlts",
      information: "value", intervention: "prediction", workloadFamily: "trace",
      idea: "예측 시점에 이미 register에 쓰여 있는 값의 요약(digest)과 분기 방향의 상관을 학습한다.",
      needs: "상관되는 값이 예측 시점에 이미 계산되어 있어야 한다.",
      baseline: "192KB TAGE-SC-L", workload: "CBP2025 trace 673개", core: "예측 정확도 평가",
      misprediction: [{ label: "ISCA 2026 확장판, trace 평균", value: 5.0 }],
      speedup: [{ label: "ISCA 2026 확장판, SPEC2017 gem5 16-wide", value: 1.55 }],
      cost: "값 관련 구성요소 약 7KB (총 예산 192KB 안)",
      evidence: "CBP2025 공개판 전문 + ISCA 2026 확장판 수치",
    },
    {
      id: "whisper", name: "Whisper", category: "C", venue: "MICRO 2022", year: 2022,
      title: "Whisper: Profile-Guided Branch Misprediction Elimination for Data Center Applications",
      authors: "Khan, Ugur, Nathella, Sunwoo, Litz, Jiménez, Kasikci",
      url: "https://takhandipu.github.io/papers/khan-whisper-micro-2022.pdf",
      chapter: "state", anchor: "whisper",
      information: "state", intervention: "prediction", workloadFamily: "server",
      idea: "Offline profile로 분기마다 간결한 Boolean 규칙을 찾아 hint 명령으로 코드에 넣는다.",
      needs: "Profile을 뜬 입력과 실제 입력의 동작이 비슷해야 한다. 코드와 링커를 바꿔야 한다.",
      baseline: "64KB TAGE-SC-L", workload: "데이터센터 응용 12개", core: "6-wide",
      misprediction: [{ label: "평균", value: 16.8 }],
      speedup: [{ label: "평균", value: 2.8 }],
      cost: "정적 코드 +11.4%, 동적 명령 +9.8%",
      evidence: "논문 전문",
    },
    {
      id: "llbp", name: "LLBP", category: "C", venue: "MICRO 2024", year: 2024,
      title: "The Last-Level Branch Predictor",
      authors: "Schall, Sandberg, Grot",
      url: "https://dhschall.github.io/assets/pdf/LLBP_MICRO24.pdf",
      chapter: "state", anchor: "llbp",
      information: "state", intervention: "prediction", workloadFamily: "server",
      idea: "큰 2차 저장소에 패턴을 문맥별로 보관하고, 곧 쓸 묶음만 작은 Pattern Buffer로 미리 가져온다.",
      needs: "다음 문맥을 미리 알 수 있어야 하고 패턴이 제때 도착해야 한다.",
      baseline: "64KB TAGE-SC-L", workload: "서버 workload 14개", core: "6-wide",
      misprediction: [{ label: "평균", value: 8.9 }],
      speedup: [{ label: "평균", value: 0.63 }],
      cost: "약 515KB 저장 공간",
      evidence: "논문 전문",
    },
    {
      id: "llbpx", name: "LLBP-X", category: "C", venue: "HPCA 2026", year: 2026,
      title: "The Last-Level Branch Predictor Revisited",
      authors: "Schall, Ďuračková, Grot",
      url: "https://dhschall.github.io/assets/pdf/LLBPX_HPCA26.pdf",
      chapter: "state", anchor: "llbpx",
      information: "state", intervention: "prediction", workloadFamily: "server",
      idea: "문맥을 나누는 깊이를 문맥마다 실행 중에 골라, 패턴의 쏠림과 중복을 함께 줄인다.",
      needs: "LLBP와 같은 조건에 더해 문맥 추적 표가 필요하다.",
      baseline: "64KB TAGE-SC-L", workload: "서버 workload 14개", core: "8-wide (gem5)",
      misprediction: [{ label: "평균", value: 12.1 }],
      speedup: [{ label: "gem5 평균", value: 1.0 }],
      cost: "LLBP에 약 9KB 추가",
      evidence: "논문 전문",
    },
    {
      id: "pure", name: "PURE", category: "C", venue: "MICRO 2026", year: 2026,
      title: "Towards a Noise-Resilient TAGE via PURE",
      authors: "Zhang, Su, Qu, He, Liu, Zhang, Zhang",
      url: "https://craft.cs.tsinghua.edu.cn/publication/towards-a-noise-resilient-tage-via-pure/",
      chapter: "state", anchor: "pure",
      information: "state", intervention: "prediction", workloadFamily: "server",
      idea: "Offline profile로 쓸모없는 패턴을 가려내 TAGE가 그 패턴에 entry를 할당하지 않게 한다.",
      needs: "Offline profile이 필요하다. 세부 구조는 공개 초록으로 확인되지 않는다.",
      baseline: "64KB TAGE-SC-L", workload: "서버 응용 12개", core: "확인되지 않음",
      misprediction: [{ label: "평균", value: 25.2 }],
      speedup: [],
      cost: "metadata 22KB",
      evidence: "공개 초록",
    },
    {
      id: "phelps", name: "Phelps", category: "D", venue: "HPCA 2025", year: 2025,
      title: "Phelps: Delinquent Loop Pre-execution Using Predicated Helper Threads",
      authors: "Seshadri, Rotenberg",
      url: "https://ericrotenberg.wordpress.ncsu.edu/files/2025/06/paper_HPCA-31_Phelps.pdf",
      chapter: "loop", anchor: "phelps",
      information: "value", intervention: "prediction", workloadFamily: "general",
      idea: "루프 안의 어려운 분기들을 조건값으로 바꿔 helper에서 미리 계산하고, 반복 단위로 결과를 맞춘다.",
      needs: "어려운 분기가 helper로 만들 수 있는 루프 안에 있어야 한다. 코어 자원을 main과 나눈다.",
      baseline: "64KB TAGE-SC-L", workload: "GAP, SPEC2006 astar, SPEC2017 정수", core: "8-wide",
      misprediction: [],
      speedup: [{ label: "astar", value: 15 }, { label: "bc", value: 63 }, { label: "bfs", value: 64 }],
      cost: "10.82KB + 코어 자원 분할",
      evidence: "논문 전문",
    },
    {
      id: "apf", name: "Alternate Path Fetch", category: "E", venue: "ISCA 2024", year: 2024,
      title: "Alternate Path Fetch",
      authors: "Deshmukh, Cai, Patt",
      url: "https://hps.ece.utexas.edu/pub/Deshmukh_APF.pdf",
      chapter: "recovery", anchor: "apf",
      information: "recovery", intervention: "afterMisprediction", workloadFamily: "general",
      idea: "틀릴 것 같은 분기의 반대 경로 명령을 미리 가져와 해석해 두고, 오예측이면 바로 공급한다.",
      needs: "어느 분기가 틀릴지 잘 골라야 한다. 쓰이지 않은 준비는 낭비다.",
      baseline: "64KB TAGE-SC-L", workload: "SPEC2017 정수 + GAP", core: "8-wide",
      misprediction: [{ label: "오예측 수는 줄이지 않는다", value: 0 }],
      speedup: [{ label: "기하평균", value: 5 }],
      cost: "별도 frontend와 buffer, 면적 약 2%",
      evidence: "논문 전문",
    },
    {
      id: "sbrb", name: "SBRB", category: "E", venue: "ISCA 2026", year: 2026,
      title: "Augmenting the Branch Predictor with a Squashed-Branch Reuse Buffer",
      authors: "Singh, Li, Rotenberg",
      url: "https://doi.org/10.1109/ISCA66397.2026.00052",
      chapter: "recovery", anchor: "sbrb",
      information: "recovery", intervention: "afterMisprediction", workloadFamily: "general",
      idea: "오예측으로 취소된 명령 가운데 이미 계산을 끝낸 분기의 결과를 저장했다가 다시 만날 때 쓴다.",
      needs: "취소되기 전에 결과가 나와 있어야 하고, 같은 실행 instance를 찾아야 한다.",
      baseline: "64KB TAGE-SC-L", workload: "SPEC2006/2017 정수 + GAP", core: "확인되지 않음",
      misprediction: [],
      speedup: [{ label: "SPEC 정수", value: 2.08 }, { label: "전체", value: 4.43 }, { label: "GAP", value: 7.25 }],
      cost: "11KB",
      evidence: "공개 초록",
    },
    {
      id: "ahead", name: "Ahead Prediction", category: "F", venue: "ISCA 2025", year: 2025,
      title: "Enabling Ahead Prediction with Practical Energy Constraints",
      authors: "Cai, Deshmukh, Patt",
      url: "https://hps.ece.utexas.edu/pub/cai_ahead.pdf",
      chapter: "latency", anchor: "ahead",
      information: "history", intervention: "prediction", workloadFamily: "general",
      idea: "느리지만 정확한 예측기의 조회를 몇 분기 앞서 시작하고, 그 사이의 history는 secondary tag로 나중에 고른다.",
      needs: "빠진 history의 조합이 실제로는 몇 개뿐이어야 한다.",
      baseline: "3-cycle overriding TAGE", workload: "SPEC CPU2017", core: "16-wide",
      misprediction: [{ label: "정확도는 거의 그대로", value: 0 }],
      speedup: [{ label: "평균", value: 4.4 }],
      cost: "+19.65KB, 예측 접근 에너지 약 1.5배",
      evidence: "논문 전문",
    },
  ];

  window.BranchBook.papers = PAPERS;
  window.BranchBook.workloadFamilies = WORKLOAD_FAMILIES;
  window.BranchBook.informationKinds = INFORMATION_KINDS;
  window.BranchBook.interventionTimes = INTERVENTION_TIMES;
})();
